[package]
name = "floem_vger_renderer"
version.workspace = true
edition = "2021"
repository = "https://github.com/lapce/floem"
description = "A native Rust UI library with fine-grained reactivity"
license.workspace = true

[dependencies]
image.workspace = true

resvg = "0.33.0"
wgpu = "0.18.0"
raw-window-handle = "0.5.1"
futures = "0.3.26"
anyhow = "1.0.69"
floem-peniko = "0.1.0"
swash = "0.1.8"
floem-vger-rs = { package = "floem-vger", version = "0.2.7" }  # Alias library to avoid overlap with subcrate
floem_renderer = { path = "../renderer", version = "0.1.0" }
