[package]
name = "floem-editor-core"
version.workspace = true
edition = "2021"
repository = "https://github.com/lapce/floem"
license.workspace = true

[dependencies]
serde.workspace = true
strum.workspace = true
strum_macros.workspace = true
tracing.workspace = true

lapce-xi-rope.workspace = true

itertools = "0.10.1"
bitflags = "1.3.2"
